version: '3'
services:
  myappdb:
    image: myapp/myappdb:1.0
  myappserver:
    image: myapp/myappserver:1.0
    ports: 
     - "80:8080"
    volumes:
     - D:/apps:/opt/tomcat/webapps
    links:
     - myappdb

