apiVersion: v1
kind: Service
metadata:
  name: myappdb
  labels:
    app: myappserver
spec:
  ports:
   - port: 3306
  selector:
    app: myappserver
    tier: myappdb
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myappdb-vol-claim
  labels:
   app: myappserver
   tier: myappdb
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  volumeMode: Filesystem
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myappdb
spec:
  selector:
    matchLabels:
      app: myappserver
      tier: myappdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: myappserver
        tier: myappdb
    spec:
      containers:
      - name: myappdb
        image: myappdb:latest
        env:
        - name: MYSQL_DB
          value: myapp
        - name: MYSQL_USER
          value: myapp
        - name: MYSQL_USERPWD
          valueFrom:
            secretKeyRef:
             name: myappdb-pass
             key: password
        - name: IP_LIST
          value: "localhost,127.0.0.1,%"
        - name: MYSQL_INIT_SQL
          value: /root/initdb.sql
        ports:
        - containerPort: 3306
          name: myappdb
        volumeMounts:
        - name: myappdb-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: myappdb-persistent-storage
        persistentVolumeClaim:
          claimName: myappdb-vol-claim
