apiVersion: v1
kind: PersistentVolume
metadata:
  name: myappdb-vol-storage
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/myappdbdata"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: myappserver-vol-storage
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/myappserverdata"
