apiVersion: v1
kind: Service
metadata:
  name: myappserver
  labels:
    app: myappserver
spec:
  ports:
   - port: 8080
  selector:
    app: myappserver
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myappserver-vol-claim
  labels:
   app: myappserver
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myappserver
spec:
  selector:
    matchLabels:
      app: myappserver
      tier: frontend
  strategy:
      type: Recreate
  template:
    metadata:
      labels:
        app: myappserver
        tier: frontend
    spec:
      containers:
      - image: myappserver:latest
        name: myappserver
        ports:
        - containerPort: 8080
          name: myappserver
        volumeMounts:
        - name: myappserver-persistent-storage
          mountPath: /opt/tomcat/webapps
      volumes:
      - name: myappserver-persistent-storage
        persistentVolumeClaim:
          claimName: myappserver-vol-claim
